server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://market.cfcloopw4xcn.us-west-2.rds.amazonaws.com:3306/market?useSSL=false
    username: root
    password: minhasenha
    driver-class: com.mysql.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update

market:
  moip:
    service:
      url: http://ec2-54-187-197-124.us-west-2.compute.amazonaws.com:8082

rest:
  timeout:
    connect: 20000
    read: 20000