server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/market?useSSL=false
    username: root
    password: minhasenha0909
    driver-class: com.mysql.jdbc.Driver

  jpa:
    database-platform:  org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update