server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/market?useSSL=false
    username: root
    password: minhasenha0909
    driver-class: com.mysql.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      ddl-auto: update

moip:
  endpoint: sandbox.moip.com.br
  token: 5WFMTKA2J0ZH8EP5E8G4I3RA86T92629
  key: DAGOUQ4BJVCEPRWXF3J6IGDTKAPLPVAUI4WV2Z5J